### ISSUE TITLE
confused

### ISSUE THREAD

**Issue by mintminty59** [crombiecrunch/yiimp#1]
lost now

**Comment by mintminty59** [comment]
Got passed that now this

Make sure you double check before hitting enter! Only one shot at these!

Enter support email (e.g. admin@example.com) : supermexxx@hotmail.com
Enter time zone (e.g. America/New_York) : europe/london
New server name (like srv.company.tld) : myyiimp
Install Fail2ban? [Y/n] : n
Send an mail to test the smtp service? [Y/n] : y
hostname: you must be root to change the host name
Server Admin contact email : supermexxx@hotmail.com
./install.sh: line 48: syntax error near unexpected token `fi'
./install.sh: line 48: `    fi'
ubuntu@ubuntu:~$

**Comment by mintminty59** [comment]
I would contact u direct

**Comment by crombiecrunch** [comment]
Issue fixed.

**Comment by crombiecrunch** [comment]
haha i broke it again. give me a few to fix it

**Comment by crombiecrunch** [comment]
ok ran the script a few times and all is well.

**Comment by crombiecrunch** [comment]
closing this as everything is working now.
