### ISSUE TITLE
Web?

### ISSUE THREAD

**Issue by DevBiiTz** [crombiecrunch/yiimp#3]
How can I view the website?

i only can view this: 
![78ddfe771258d3e7f4af7a08373084f0](https://user-images.githubusercontent.com/30190276/29879463-6b0dc730-8da5-11e7-869b-6371ea8d0a02.png)

**Comment by DevBiiTz** [comment]
i change this of default in the site enabled nginx:
![3f3ebf394262e46618a95d96aecae3c2](https://user-images.githubusercontent.com/30190276/29879838-84a6e64e-8da6-11e7-9ddf-a4bcfac6a422.png)
And i can see this:
![a57380d8d04c6d0d07919b5d7c5fb5f0](https://user-images.githubusercontent.com/30190276/29879906-b56c93be-8da6-11e7-9189-49c01938d4f3.png)
Sorry my english im spanish

**Comment by crombiecrunch** [comment]
ahhh its an error in the script try going to http(s)://yourip or http(s)://yourdomain
:

**Comment by DevBiiTz** [comment]
![c999df295249eee475ae06927e396380](https://user-images.githubusercontent.com/30190276/29898992-0a2bc432-8de9-11e7-8fc2-274b2c6b2423.png)

**Comment by DevBiiTz** [comment]
Working

**Comment by crombiecrunch** [comment]
Great, its just the nginx config does have the correct redirect. ill update it soon
